env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:yml/standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
overrides:
  - files: '*.yml'
    parser: yaml-eslint-parser
plugins:
  - react
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - never
  # we need to disable the JS version of this rule, and then enable the typescript version
  no-use-before-define:
    - off
  '@typescript-eslint/no-use-before-define':
    - error
  quotes:
    - error
    - single
  jsx-quotes:
    - error
    - prefer-single
  yml/sort-keys:
    - error
    - pathPattern: ^people.*$
      order:
        - name
        - country
        - born
        - father
        - mother
        - reign
settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
      moduleDirectory:
        - node_modules
        - src
  react:
    version: detect
