version: 2.1
executors:
  node-lts-executor:
    docker:
      - image: cimg/node:lts
jobs:
  build:
    executor: node-lts-executor
    steps:
      # Build the project from scratch
      - checkout
      - run: |
          yarn
          yarn build
  init:
    executor: node-lts-executor
    steps:
      # Initialize and install dev dependencies so that we can lint and test
      - checkout
      - run: yarn --dev
  lint:
    executor: node-lts-executor
    steps:
      - run: yarn lint
  test:
    executor: node-lts-executor
    steps:
      - run: yarn test
workflows:
  main:
    jobs:
      - init
      - lint:
          requires: init
      - test
          requires: init
      - build
