version: 2.1
executors:
  node-lts-executor:
    docker:
      - image: cimg/node:lts
jobs:
  build:
    executor: node-lts-executor
    steps:
      # Build the project from scratch
      - checkout
      - run: |
          npm install
          npm run build
  lint:
    executor: node-lts-executor
    steps:
      - checkout
      - run: |
          npm install
          npm run lint
  test:
    executor: node-lts-executor
    steps:
      - checkout
      - run: |
          npm install --save-dev
          npm test
workflows:
  main:
    jobs:
      - lint:
          filters:
            branches:
              ignore: gh-pages
      - test:
          filters:
            branches:
              ignore: gh-pages
      - build:
          filters:
            branches:
              ignore: gh-pages
