version: 2.1
executors:
  node-lts-executor:
    docker:
      - image: cimg/node:lts
jobs:
  build:
    executor: node-lts-executor
    steps:
      - run: yarn --dev
  lint:
    executor: node-lts-executor
    steps:
      - run: yarn lint
  test:
    executor: node-lts-executor
    steps:
      - run: yarn test
workflows:
  main:
    jobs:
      - build
      - lint
      - test
